# Generated by Django 3.0.4 on 2023-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230619_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='lived_in',
            field=models.ManyToManyField(blank=True, null=True, related_name='lived_in_house', to='main.UserAccount'),
        ),
    ]
