# Generated by Django 3.0.4 on 2023-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230619_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='lived_in',
            field=models.ManyToManyField(blank=True, related_name='lived_in_house', to='main.UserAccount'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
