# Generated by Django 3.0.4 on 2023-06-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230621_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='listed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AgentAccount'),
        ),
    ]
