# Generated by Django 3.0.4 on 2023-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230621_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='No name', max_length=100),
        ),
    ]
