# Generated by Django 3.0.4 on 2023-06-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_room_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AgentAccount')),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserAccount')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.House')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Room')),
            ],
        ),
    ]
