# Generated by Django 3.0.4 on 2023-06-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
