# Generated by Django 3.0.4 on 2023-06-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230622_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccount',
            name='phone_number',
            field=models.CharField(default='0123456789', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='0123456789', max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GrantedBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pay_before', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.AgentAccount')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserAccount')),
            ],
        ),
    ]
