# Generated by Django 3.0.4 on 2023-06-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230623_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
