# Generated by Django 3.0.4 on 2023-06-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230627_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantedbookings',
            name='pay_before',
        ),
    ]
