# Generated by Django 3.0.4 on 2023-06-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_grantedbookings_pay_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantedbookings',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Booking'),
        ),
    ]
