# Generated by Django 3.0.4 on 2023-07-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_agentaccount_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
