# Generated by Django 3.0.4 on 2023-07-12 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_house_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='date_listed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
